### ISSUE TITLE
All dockings do not work because there's no gridding process.

### ISSUE THREAD

**Issue by yipy0005** [KeenThera/SECSE#3]
Hi, I was trying out the repo when I realised that neither the autodock nor glide is able to run because there was no gridding process, resulting in no grid files. >.<

**Comment by ChongLu121** [comment]
Hi!

Based on different understandings of targets and pockets, people will treat pockets differently, so preprocessing of proteins may not be a relatively standardized process. The tool requires the prepared target grid as input. 

I just uploaded the .pdbqt file of the demo.  If you want to calculate other proteins, you may need to preprocess them with additional software. 

Best,
Chong

**Comment by yipy0005** [comment]
I see. For autodock-gpu, it would require the protein.maps.fld for the ffile argument. But I realised your code fed the receptor pdbqt file instead. Does that mean I can run autodock-gpu without the that grid file or I would have to generate the grid file myself and change the code to change the argument input instead?

Thank you so much for answering my queries. :)

**Comment by ChongLu121** [comment]
For autodock-gpu:  the **target** parameter in the config file is the path of <protein>.maps.fld, and all other necessary *map files should also be in the same folder.  Then it will work. :)
