### ISSUE TITLE
Problem running demo

### ISSUE THREAD

**Issue by BW15061999** [KeenThera/SECSE#4]
Hi!

When I try to run the demo with the command below.
`python $SECSE/run_secse.py --config demo/phgdh_demo_vina.ini`

It generates  **pandas.errors.EmptyDataError: No columns to parse from file**, what should I do to solve it? 
Thank you!

**Here is the output**
 ```
**************************************************************************************** 
       ____    _____    ____   ____    _____ 
      / ___|  | ____|  / ___| / ___|  | ____|
      \___ \  |  _|   | |     \___ \  |  _|  
       ___) | | |___  | |___   ___) | | |___ 
      |____/  |_____|  \____| |____/  |_____|
/home/bruce/Downloads/Softwares/Anaconda/envs/secse/lib/python3.7/site-packages/pandas/core/generic.py:2882: UserWarning: The spaces in these column names will not be changed. In pandas versions < 0.14, spaces were converted to underscores.
  method=method,
Table 'G-001' already exists.

******************************************************************
Input fragment file: /home/bruce/Work/CADD/SECSE/code/demo/demo_1020.smi
Target grid file: /home/bruce/Work/CADD/SECSE/code/demo/PHGDH_6RJ3_for_vina.pdbqt
Workdir: /home/bruce/Work/CADD/SECSE/code/res/


 ************************************************** 
Generation  0 ...
Step 1: Docking with Autodock Vina ...
/home/bruce/Work/CADD/SECSE/code/secse/evaluate/ligprep_vina_parallel.sh /home/bruce/Work/CADD/SECSE/code/res/generation_0 /home/bruce/Work/CADD/SECSE/code/demo/demo_1020.smi /home/bruce/Work/CADD/SECSE/code/demo/PHGDH_6RJ3_for_vina.pdbqt 20.9 -10.4 3.0 20.0 20.0 25.0 10
find /home/bruce/Work/CADD/SECSE/code/res/generation_0/sdf_files -name "*sdf" | xargs -n 100 cat > /home/bruce/Work/CADD/SECSE/code/res/generation_0/docking_outputs_with_score.sdf
Docking time cost: 0.12 min.
Step 2: Ranking docked molecules...
9 cmpds after evaluate
The evaluate score cutoff is: -9.0
9 final seeds.

 ************************************************** 
Generation  1 ...
Step 1: Mutation
No rule class:  B-001
No rule class:  G-003
No rule class:  G-004
No rule class:  G-005
No rule class:  G-006
No rule class:  G-007
No rule class:  M-001
No rule class:  M-002
No rule class:  M-003
No rule class:  M-004
No rule class:  M-005
No rule class:  M-006
No rule class:  M-007
No rule class:  M-008
No rule class:  M-009
No rule class:  M-010
No rule class: G-002
Step 2: Filtering all mutated mols
sh /home/bruce/Work/CADD/SECSE/code/secse/growing/filter_parallel.sh /home/bruce/Work/CADD/SECSE/code/res/generation_1 1 demo/phgdh_demo_vina.ini 10
Filter runtime: 0.00 min.
Traceback (most recent call last):
  File "/home/bruce/Work/CADD/SECSE/code/secse/run_secse.py", line 80, in <module>
    main()
  File "/home/bruce/Work/CADD/SECSE/code/secse/run_secse.py", line 65, in main
    workflow.grow()
  File "/home/bruce/Work/CADD/SECSE/code/secse/grow_processes.py", line 208, in grow
    self._filter_df = pd.read_csv(os.path.join(self.workdir_now, "filter.csv"), header=None)
  File "/home/bruce/Downloads/Softwares/Anaconda/envs/secse/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/bruce/Downloads/Softwares/Anaconda/envs/secse/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/bruce/Downloads/Softwares/Anaconda/envs/secse/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/bruce/Downloads/Softwares/Anaconda/envs/secse/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/bruce/Downloads/Softwares/Anaconda/envs/secse/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/bruce/Downloads/Softwares/Anaconda/envs/secse/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 69, in __init__
    self._reader = parsers.TextReader(self.handles.handle, **kwds)
  File "pandas/_libs/parsers.pyx", line 549, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file
```

**Comment by zhentg** [comment]
I met similar issue:

 python $SECSE/run_secse.py --config phgdh_demo_vina.ini                                                                             
 ****************************************************************************************
       ____    _____    ____   ____    _____
      / ___|  | ____|  / ___| / ___|  | ____|
      \___ \  |  _|   | |     \___ \  |  _|
       ___) | | |___  | |___   ___) | | |___
      |____/  |_____|  \____| |____/  |_____|

******************************************************************
Input fragment file: /home/zhentg/nfs/sandbox/SECSE/SECSE-1.0.0/demo/demo_1020.smi
Target grid file: /home/zhentg/nfs/sandbox/SECSE/SECSE-1.0.0/demo/6rj3A_pro.pdbqt
Workdir: /home/zhentg/nfs/sandbox/SECSE/SECSE-1.0.0/demo

Step 1: Docking with Autodock Vina ...
/opt/userdata/zhentg/sandbox/SECSE/SECSE-1.0.0/secse/evaluate/ligprep_vina_parallel.sh /home/zhentg/nfs/sandbox/SECSE/SECSE-1.0.0/demo/generation_0 /home/zhentg/nfs/sandbox/SECSE/SECSE-1.0.0/demo/demo_1020.smi /home/zhentg/nfs/sandbox/SECSE/SECSE-1.0.0/demo/6rj3A_pro.pdbqt 20.9 -10.4 3.0 20.0 20.0 25.0 10
find /home/zhentg/nfs/sandbox/SECSE/SECSE-1.0.0/demo/generation_0/sdf_files -name "*sdf" | xargs -n 100 cat > /home/zhentg/nfs/sandbox/SECSE/SECSE-1.0.0/demo/generation_0/docking_outputs_with_score.sdf
Docking time cost: 0.07 min.
Step 2: Ranking docked molecules...
9 cmpds after evaluate
The evaluate score cutoff is: -9.0
9 final seeds.

 **************************************************
Generation  1 ...
Step 1: Mutation
Step 2: Filtering all mutated mols
sh /opt/userdata/zhentg/sandbox/SECSE/SECSE-1.0.0/secse/growing/filter_parallel.sh /home/zhentg/nfs/sandbox/SECSE/SECSE-1.0.0/demo/generation_1 1 phgdh_demo_vina.ini 10
Filter runtime: 0.01 min.
Traceback (most recent call last):
  File "/opt/userdata/zhentg/sandbox/SECSE/SECSE-1.0.0/secse/run_secse.py", line 70, in <module>
    main()
  File "/opt/userdata/zhentg/sandbox/SECSE/SECSE-1.0.0/secse/run_secse.py", line 55, in main
    workflow.grow()
  File "/opt/userdata/zhentg/sandbox/SECSE/SECSE-1.0.0/secse/grow_processes.py", line 183, in grow
    self._filter_df = pd.read_csv(os.path.join(self.workdir_now, "filter.csv"), header=None)

**Comment by ChongLu121** [comment]
Hi!

Thanks for your feedback, there is a bug in the code. Please fetch the code again.

If you want to use the default rule database, set the rule_db parameter to 0. If you want to use custom rules, you need to add more rules to the JSON file.
The SMARTS examples in the current demo JSON file are only for the definition of the format and cannot generate enough molecules, resulting in the filter.csv file being empty. 

Please reload the code and change rule_db to 0 and run again.

Best,
Chong

**Comment by yipy0005** [comment]
Hi, I met with the same problem as the previous 2 users, but my rules_db was already set to 0. >.<

**Comment by ChongLu121** [comment]
I just fixed a bug in the code, please download the newer version.

The empty file may be caused by incompatible xlrd versions. 
Please install xlrd  v2.0.1: `conda install -c anaconda xlrd` or  `pip install xlrd`

And enter the **absolute path** of the config file.

**Comment by zhentg** [comment]
Thanks, Chong,

Following your suggestion ,below is my step-by-step workflow, and the demo works now!

#Download

- <https://github.com/KeenThera/SECSE>
- cd /sandbox/SECSE
- unzip SECSE-master.zip

#Installation

- conda create -n SECSE
- conda activate SECSE
- conda install -y numpy=1.20.3 pandas=1.3.3 pandarallel=1.5.2  tqdm=4.62.2 biopandas=0.2.9 openbabel=3.1.1 rdkit=2021.03.5 chemprop=1.3.1 xlrd
- export SECSE=/sandbox/SECSE/SECSE-master/secse
- export VINA=/tools/autodockVina/vina
- chmod +x -R $SECSE

    #install GNU parallel

- wget http://ftp.gnu.org/gnu/parallel/parallel-latest.tar.bz2 <http://ftp.gnu.org/gnu/parallel/parallel-latest.tar.bz2>
- tar xjf /opt/downloads/parallel-latest.tar.bz2
- sudo ./configure && make && make install



#Demo run

-  cd $SECSE; cd ../demo
  - python $SECSE/run_secse.py --config /sandbox/SECSE/SECSE-master/demo/phgdh_demo_vina.ini

**Comment by yipy0005** [comment]
It's really strange. I did all I could and it gave the following error:

```
 ****************************************************************************************
       ____    _____    ____   ____    _____
      / ___|  | ____|  / ___| / ___|  | ____|
      \___ \  |  _|   | |     \___ \  |  _|
       ___) | | |___  | |___   ___) | | |___
      |____/  |_____|  \____| |____/  |_____|

******************************************************************
Input fragment file: /home/yipyewmun/Github/SECSE/demo/demo_1020.smi
Target grid file: /home/yipyewmun/Github/SECSE/demo/PHGDH_6RJ3_for_vina.pdbqt
Workdir: /home/yipyewmun/Github/SECSE/demo/


 **************************************************
Generation  0 ...
Step 1: Docking with Autodock Vina ...
/home/yipyewmun/Github/SECSE/secse/evaluate/ligprep_vina_parallel.sh /home/yipyewmun/Github/SECSE/demo/generation_0 /home/yipyewmun/Github/SECSE/demo/demo_1020.smi /home/yipyewmun/Github/SECSE/demo/PHGDH_6RJ3_for_vina.pdbqt 20.9 -10.4 3.0 20.0 20.0 25.0 5
find /home/yipyewmun/Github/SECSE/demo/generation_0/sdf_files -name "*sdf" | xargs -n 100 cat > /home/yipyewmun/Github/SECSE/demo/generation_0/docking_outputs_with_score.sdf
Docking time cost: 0.06 min.
Step 2: Ranking docked molecules...
9 cmpds after evaluate
The evaluate score cutoff is: -9.0
9 final seeds.

 **************************************************
Generation  1 ...
Step 1: Mutation
Step 2: Filtering all mutated mols
sh /home/yipyewmun/Github/SECSE/secse/growing/filter_parallel.sh /home/yipyewmun/Github/SECSE/demo/generation_1 1 /home/yipyewmun/Github/SECSE/demo/phgdh_demo_vina.ini 5
Filter runtime: 0.00 min.
Traceback (most recent call last):
  File "/home/yipyewmun/Github/SECSE/secse/run_secse.py", line 80, in <module>
    main()
  File "/home/yipyewmun/Github/SECSE/secse/run_secse.py", line 65, in main
    workflow.grow()
  File "/home/yipyewmun/Github/SECSE/secse/grow_processes.py", line 208, in grow
    self._filter_df = pd.read_csv(os.path.join(self.workdir_now, "filter.csv"), header=None)
  File "/home/yipyewmun/anaconda3/envs/secse_py39/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/yipyewmun/anaconda3/envs/secse_py39/lib/python3.9/site-packages/pandas/io/parsers.py", line 462, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/yipyewmun/anaconda3/envs/secse_py39/lib/python3.9/site-packages/pandas/io/parsers.py", line 819, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/yipyewmun/anaconda3/envs/secse_py39/lib/python3.9/site-packages/pandas/io/parsers.py", line 1050, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/yipyewmun/anaconda3/envs/secse_py39/lib/python3.9/site-packages/pandas/io/parsers.py", line 1898, in __init__
    self._reader = parsers.TextReader(self.handles.handle, **kwds)
  File "pandas/_libs/parsers.pyx", line 521, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file
```

**Comment by ChongLu121** [comment]
> It's really strange. I did all I could and it gave the following error:
> 
> ```
>  ****************************************************************************************
>        ____    _____    ____   ____    _____
>       / ___|  | ____|  / ___| / ___|  | ____|
>       \___ \  |  _|   | |     \___ \  |  _|
>        ___) | | |___  | |___   ___) | | |___
>       |____/  |_____|  \____| |____/  |_____|
> 
> ******************************************************************
> Input fragment file: /home/yipyewmun/Github/SECSE/demo/demo_1020.smi
> Target grid file: /home/yipyewmun/Github/SECSE/demo/PHGDH_6RJ3_for_vina.pdbqt
> Workdir: /home/yipyewmun/Github/SECSE/demo/
> 
> 
>  **************************************************
> Generation  0 ...
> Step 1: Docking with Autodock Vina ...
> /home/yipyewmun/Github/SECSE/secse/evaluate/ligprep_vina_parallel.sh /home/yipyewmun/Github/SECSE/demo/generation_0 /home/yipyewmun/Github/SECSE/demo/demo_1020.smi /home/yipyewmun/Github/SECSE/demo/PHGDH_6RJ3_for_vina.pdbqt 20.9 -10.4 3.0 20.0 20.0 25.0 5
> find /home/yipyewmun/Github/SECSE/demo/generation_0/sdf_files -name "*sdf" | xargs -n 100 cat > /home/yipyewmun/Github/SECSE/demo/generation_0/docking_outputs_with_score.sdf
> Docking time cost: 0.06 min.
> Step 2: Ranking docked molecules...
> 9 cmpds after evaluate
> The evaluate score cutoff is: -9.0
> 9 final seeds.
> 
>  **************************************************
> Generation  1 ...
> Step 1: Mutation
> Step 2: Filtering all mutated mols
> sh /home/yipyewmun/Github/SECSE/secse/growing/filter_parallel.sh /home/yipyewmun/Github/SECSE/demo/generation_1 1 /home/yipyewmun/Github/SECSE/demo/phgdh_demo_vina.ini 5
> Filter runtime: 0.00 min.
> Traceback (most recent call last):
>   File "/home/yipyewmun/Github/SECSE/secse/run_secse.py", line 80, in <module>
>     main()
>   File "/home/yipyewmun/Github/SECSE/secse/run_secse.py", line 65, in main
>     workflow.grow()
>   File "/home/yipyewmun/Github/SECSE/secse/grow_processes.py", line 208, in grow
>     self._filter_df = pd.read_csv(os.path.join(self.workdir_now, "filter.csv"), header=None)
>   File "/home/yipyewmun/anaconda3/envs/secse_py39/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
>     return _read(filepath_or_buffer, kwds)
>   File "/home/yipyewmun/anaconda3/envs/secse_py39/lib/python3.9/site-packages/pandas/io/parsers.py", line 462, in _read
>     parser = TextFileReader(filepath_or_buffer, **kwds)
>   File "/home/yipyewmun/anaconda3/envs/secse_py39/lib/python3.9/site-packages/pandas/io/parsers.py", line 819, in __init__
>     self._engine = self._make_engine(self.engine)
>   File "/home/yipyewmun/anaconda3/envs/secse_py39/lib/python3.9/site-packages/pandas/io/parsers.py", line 1050, in _make_engine
>     return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
>   File "/home/yipyewmun/anaconda3/envs/secse_py39/lib/python3.9/site-packages/pandas/io/parsers.py", line 1898, in __init__
>     self._reader = parsers.TextReader(self.handles.handle, **kwds)
>   File "pandas/_libs/parsers.pyx", line 521, in pandas._libs.parsers.TextReader.__cinit__
> pandas.errors.EmptyDataError: No columns to parse from file
> ```

Hi,
I'm currently not sure what the exact reason is. We need a few steps to find the problem.

1.  replace your secse folder by [secse.zip](https://github.com/KeenThera/SECSE/files/8448228/secse.zip).
2.  Run the same command again.  `python $SECSE/run_secse.py --config /your/config/absolute/path`
3. After your see the EmptyDataError, run
```
sh /home/yipyewmun/Github/SECSE/secse/growing/filter_parallel.sh /home/yipyewmun/Github/SECSE/demo/generation_1 1 /home/yipyewmun/Github/SECSE/demo/phgdh_demo_vina.ini 5
```
Let me know the new error message.

**Comment by BW15061999** [comment]
> > It's really strange. I did all I could and it gave the following error:
> > ```
> >  ****************************************************************************************
> >        ____    _____    ____   ____    _____
> >       / ___|  | ____|  / ___| / ___|  | ____|
> >       \___ \  |  _|   | |     \___ \  |  _|
> >        ___) | | |___  | |___   ___) | | |___
> >       |____/  |_____|  \____| |____/  |_____|
> > 
> > ******************************************************************
> > Input fragment file: /home/yipyewmun/Github/SECSE/demo/demo_1020.smi
> > Target grid file: /home/yipyewmun/Github/SECSE/demo/PHGDH_6RJ3_for_vina.pdbqt
> > Workdir: /home/yipyewmun/Github/SECSE/demo/
> > 
> > 
> >  **************************************************
> > Generation  0 ...
> > Step 1: Docking with Autodock Vina ...
> > /home/yipyewmun/Github/SECSE/secse/evaluate/ligprep_vina_parallel.sh /home/yipyewmun/Github/SECSE/demo/generation_0 /home/yipyewmun/Github/SECSE/demo/demo_1020.smi /home/yipyewmun/Github/SECSE/demo/PHGDH_6RJ3_for_vina.pdbqt 20.9 -10.4 3.0 20.0 20.0 25.0 5
> > find /home/yipyewmun/Github/SECSE/demo/generation_0/sdf_files -name "*sdf" | xargs -n 100 cat > /home/yipyewmun/Github/SECSE/demo/generation_0/docking_outputs_with_score.sdf
> > Docking time cost: 0.06 min.
> > Step 2: Ranking docked molecules...
> > 9 cmpds after evaluate
> > The evaluate score cutoff is: -9.0
> > 9 final seeds.
> > 
> >  **************************************************
> > Generation  1 ...
> > Step 1: Mutation
> > Step 2: Filtering all mutated mols
> > sh /home/yipyewmun/Github/SECSE/secse/growing/filter_parallel.sh /home/yipyewmun/Github/SECSE/demo/generation_1 1 /home/yipyewmun/Github/SECSE/demo/phgdh_demo_vina.ini 5
> > Filter runtime: 0.00 min.
> > Traceback (most recent call last):
> >   File "/home/yipyewmun/Github/SECSE/secse/run_secse.py", line 80, in <module>
> >     main()
> >   File "/home/yipyewmun/Github/SECSE/secse/run_secse.py", line 65, in main
> >     workflow.grow()
> >   File "/home/yipyewmun/Github/SECSE/secse/grow_processes.py", line 208, in grow
> >     self._filter_df = pd.read_csv(os.path.join(self.workdir_now, "filter.csv"), header=None)
> >   File "/home/yipyewmun/anaconda3/envs/secse_py39/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
> >     return _read(filepath_or_buffer, kwds)
> >   File "/home/yipyewmun/anaconda3/envs/secse_py39/lib/python3.9/site-packages/pandas/io/parsers.py", line 462, in _read
> >     parser = TextFileReader(filepath_or_buffer, **kwds)
> >   File "/home/yipyewmun/anaconda3/envs/secse_py39/lib/python3.9/site-packages/pandas/io/parsers.py", line 819, in __init__
> >     self._engine = self._make_engine(self.engine)
> >   File "/home/yipyewmun/anaconda3/envs/secse_py39/lib/python3.9/site-packages/pandas/io/parsers.py", line 1050, in _make_engine
> >     return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
> >   File "/home/yipyewmun/anaconda3/envs/secse_py39/lib/python3.9/site-packages/pandas/io/parsers.py", line 1898, in __init__
> >     self._reader = parsers.TextReader(self.handles.handle, **kwds)
> >   File "pandas/_libs/parsers.pyx", line 521, in pandas._libs.parsers.TextReader.__cinit__
> > pandas.errors.EmptyDataError: No columns to parse from file
> > ```
> 
> Hi, I'm currently not sure what the exact reason is. We need a few steps to find the problem.
> 
> 1. replace your secse folder by [secse.zip](https://github.com/KeenThera/SECSE/files/8448228/secse.zip).
> 2. Run the same command again.  `python $SECSE/run_secse.py --config /your/config/absolute/path`
> 3. After your see the EmptyDataError, run
> 
> ```
> sh /home/yipyewmun/Github/SECSE/secse/growing/filter_parallel.sh /home/yipyewmun/Github/SECSE/demo/generation_1 1 /home/yipyewmun/Github/SECSE/demo/phgdh_demo_vina.ini 5
> ```
> 
> Let me know the new error message.

Hi,
As in my case, it returns
`cd: /home/SECSE/SECSE/res/generation_1/generation_split_by_seed: No such file or directory`

**Comment by ChongLu121** [comment]
@BW15061999  Did you use the new code [secse.zip](https://github.com/KeenThera/SECSE/files/8448228/secse.zip) ? In order to find the problem I modified part of the code, please download and use this version.

**Comment by BW15061999** [comment]
@ChongLu121 
Hi,
It run successfully with the code `sh /home/yipyewmun/Github/SECSE/secse/growing/filter_parallel.sh /home/yipyewmun/Github/SECSE/demo/generation_1 1 /home/yipyewmun/Github/SECSE/demo/phgdh_demo_vina.ini 5`

and the output is
```
0% 0:3=0s f3-dp1.csv /home/bruce/Work/CADD/SECSE/SECSE/res/generation_1 1 /home//home/bruce/Work/CADD/SECSE/SECSE/demo/phgdh_demo_vina.ini
33% 1:2=3s f3-dp1.csv /home/bruce/Work/CADD/SECSE/SECSE/res/generation_1 1 /home/home/bruce/Work/CADD/SECSE/SECSE/demo/phgdh_demo_vina.ini
66% 2:1=4s f3-dp1.csv /home/bruce/Work/CADD/SECSE/SECSE/res/generation_1 1 /home/home/bruce/Work/CADD/SECSE/SECSE/demo/phgdh_demo_vina.ini
100% 3:0=0s f3-dp1.csv /home/bruce/Work/CADD/SECSE/SECSE/res/generation_1 1 
```
but still the output of the `python $SECSE/run_secse.py --config /your/config/absolute/path` is  
```
sh /home/bruce/Work/CADD/SECSE/SECSE/secse/growing/filter_parallel.sh /home/bruce/Work/CADD/SECSE/SECSE/res/generation_1 1 /home/bruce/Work/CADD/SECSE/SECSE/demo/phgdh_demo_vina.ini 10
Filter runtime: 0.00 min.
Traceback (most recent call last):
  File "/home/bruce/Work/CADD/SECSE/SECSE/secse/run_secse.py", line 80, in <module>
    main()
  File "/home/bruce/Work/CADD/SECSE/SECSE/secse/run_secse.py", line 65, in main
    workflow.grow()
  File "/home/bruce/Work/CADD/SECSE/SECSE/secse/grow_processes.py", line 208, in grow
    self._filter_df = pd.read_csv(os.path.join(self.workdir_now, "filter.csv"), header=None)
  File "/home/bruce/Downloads/Softwares/Anaconda/envs/secse/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/bruce/Downloads/Softwares/Anaconda/envs/secse/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/bruce/Downloads/Softwares/Anaconda/envs/secse/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/bruce/Downloads/Softwares/Anaconda/envs/secse/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/bruce/Downloads/Softwares/Anaconda/envs/secse/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/bruce/Downloads/Softwares/Anaconda/envs/secse/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 69, in __init__
    self._reader = parsers.TextReader(self.handles.handle, **kwds)
  File "pandas/_libs/parsers.pyx", line 549, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file
```

**Comment by ChongLu121** [comment]
@BW15061999 could you please upload the file **generation_1/generation.csv** ?  Let's check if the molecules are generated in the correct way.

**Comment by BW15061999** [comment]
[generation.csv](https://github.com/KeenThera/SECSE/files/8458706/generation.csv)

**Comment by ChongLu121** [comment]
> [generation.csv](https://github.com/KeenThera/SECSE/files/8458706/generation.csv)
Molecules are generated correctly. 

If the command 
```
sh /home/bruce/Work/CADD/SECSE/SECSE/secse/growing/filter_parallel.sh /home/bruce/Work/CADD/SECSE/SECSE/res/generation_1 1 /home/bruce/Work/CADD/SECSE/SECSE/demo/phgdh_demo_vina.ini 10
```
runs successfully，you will see  "Filter runtime: 0.20 min."

The bash script filter_parallel.sh didn't finish running. Did you find any other errors when running again?

Are the output files in the folder generation_1/filter_flag  all empty files?

**Comment by BW15061999** [comment]
Hi,
the command returns `grep: *.csv: No such file or directory`
and the **generation_1/filter_flag** folder is empty

**Comment by TAEUKHAM** [comment]
Hi, thanks for sharing the code:) I think I've followed all the instructions but keep encountering this `KeyError` from the start. Seems like the code is not generating any molecules. All the routes of vina and $SECSE looks fine to me. And I've also changed the secse folder with the new one too. Would be glad to know why this is happening to me. Thanks


```
python $SECSE/run_secse.py --config /home/htw/work/SECSE/demo/phgdh_demo_vina.ini

 **************************************************************************************** 
       ____    _____    ____   ____    _____ 
      / ___|  | ____|  / ___| / ___|  | ____|
      \___ \  |  _|   | |     \___ \  |  _|  
       ___) | | |___  | |___   ___) | | |___ 
      |____/  |_____|  \____| |____/  |_____|

******************************************************************
Input fragment file: /home/htw/work/SECSE/demo/demo_1020.smi
Target grid file: /home/htw/work/SECSE/demo/PHGDH_6RJ3_for_vina.pdbqt
Workdir: /home/htw/work/SECSE/res


 ************************************************** 
Generation  0 ...
Step 1: Docking with Autodock Vina ...
/home/htw/work/SECSE/secse/evaluate/ligprep_vina_parallel.sh /home/htw/work/SECSE/res/generation_0 /home/htw/work/SECSE/demo/demo_1020.smi /home/htw/work/SECSE/demo/PHGDH_6RJ3_for_vina.pdbqt 20.9 -10.4 3.0 20.0 20.0 25.0 10
find /home/htw/work/SECSE/res/generation_0/sdf_files -name "*sdf" | xargs -n 100 cat > /home/htw/work/SECSE/res/generation_0/docking_outputs_with_score.sdf
Docking time cost: 0.01 min.
Step 2: Ranking docked molecules...
Traceback (most recent call last):
  File "/home/htw/work/SECSE/secse/run_secse.py", line 80, in <module>
    main()
  File "/home/htw/work/SECSE/secse/run_secse.py", line 65, in main
    workflow.grow()
  File "/home/htw/work/SECSE/secse/grow_processes.py", line 166, in grow
    self.ranking_docked_mols(step)
  File "/home/htw/work/SECSE/secse/grow_processes.py", line 107, in ranking_docked_mols
    ranking = Ranking(sdf=self.lig_sdf, gen=self.gen, config_file=self.config_path)
  File "/home/htw/work/SECSE/secse/scoring/ranking.py", line 62, in __init__
    self.load_sdf()
  File "/home/htw/work/SECSE/secse/scoring/ranking.py", line 70, in load_sdf
    raw_df = PandasTools.LoadSDF(self.sdf, smilesName='smiles', molColName='Molecule')[
  File "/home/htw/anaconda3/envs/SECSE/lib/python3.9/site-packages/pandas/core/frame.py", line 3464, in __getitem__
    indexer = self.loc._get_listlike_indexer(key, axis=1)[1]
  File "/home/htw/anaconda3/envs/SECSE/lib/python3.9/site-packages/pandas/core/indexing.py", line 1314, in _get_listlike_indexer
    self._validate_read_indexer(keyarr, indexer, axis)
  File "/home/htw/anaconda3/envs/SECSE/lib/python3.9/site-packages/pandas/core/indexing.py", line 1374, in _validate_read_indexer
    raise KeyError(f"None of [{key}] are in the [{axis_name}]")
KeyError: "None of [Index(['ID', 'Molecule', 'smiles', 'docking score'], dtype='object')] are in the [columns]"
```

**Comment by ChongLu121** [comment]
@TAEUKHAM It looks like your docking program didn't run successfully. Please check the environment variable $VINA or GNU parallel. Test command `$VINA` or `parallel`. If both work, check if the output folder allows writing permissions.
 Here https://github.com/KeenThera/SECSE/issues/4#issuecomment-1091116925 are the complete steps that may help you.

**Comment by TAEUKHAM** [comment]
@ChongLu121 Thanks! After resetting the path $VINA, I've solved the problem. 

@BW15061999 @yipy0005 I've encountered the same error as yours and figured out that RANDOM variable in filter.parallel.sh was the problem. Try adding a new line

`RANDOM=$$`

inside secse/growing/filter_parallel.sh
