### ISSUE TITLE
sharing rules is good 

### ISSUE THREAD

**Issue by boyuezhong** [KeenThera/SECSE#5]
Hi, Can you share more rules?

**Comment by ChongLu121** [comment]
Hi @boyuezhong , 

thank you for your interest in our project. Unfortunately, we cannot share the complete rule database publicly on GitHub at this time. If you would like to discuss it further or are interested in other collaboration possibilities, please feel free to contact us through email at lu_chong@keenthera.com. 

Thank you for your understanding.

Best,
Chong
